config/routes.rb
Rails.application.routes.draw do
  get "login" => "login#new"
  post "login" => "login#create"
  delete "logout" => "login#destroy", as: "logout"

  get "signup" => "signup#new"
  post "signup" => "signup#create"

  resources :students do
    collection do
      post "pick"
    end
  end

  root 'students#index'

end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :picks

  def name
    [first_name, last_name].join(" ")
  end

  def name=(name)
    name_components = name.split
    self.first_name = name_components.first
    self.last_name = name_components.last
  end

  def pick!
    logger.info "PICKING #{name}"
    Pick.create(student_id: id)
  end

  def count
    picks.count
  end

  def self.fairly_pick
    students = Student.all
    lowest_participation = students.map { |s| s.count }.min

    students_on_deck = students.select { |student| student.count == lowest_participation }

    picked_student = students_on_deck.sample

    logger.info "Out of #{students.length}. #{picked_student.name} gets to answer!"

    picked_student.pick!

    picked_student
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: :true, uniqueness: true
  validates :password, confirmation: true

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(password)
    @password = BCrypt::Password.create(password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate!
    redirect_to(login_path) unless current_user
  end

  def current_user
    @user ||= User.where(id: session[:user_id]).first
  end

  helper_method :current_user
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: user_params[:email])
    if @user && @user.password == user_params[:password]
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil if current_user
    redirect_to login_path
  end

  def user_params
    params.permit(:email, :password)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new, status: :unauthorized
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate!

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)

    redirect_to action: "show", id: @student.id
  end

  def create
    @student = Student.create(student_params)

    redirect_to action: "show", id: @student.id
  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to action: "index"
  end

  def pick
    @student = Student.fairly_pick
    redirect_to action: "show", id: @student.id
  end

  private

  def student_params
    params.require(:student).permit(:name, :photo_url, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>SortingTrain</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a href="#" class="navbar-brand">Sorting Train</a></li>
          <li><%= link_to "Students", students_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <p class="navbar-text">
              <% if current_user %>
                Welcome, <%= current_user.email %>!
              <% end %>
            </p>
          </li>
          <li>
            <%= link_to "Logout", logout_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/new.html.erb
<h1>Login</h1>

<%= form_tag login_path do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= text_field_tag :email, nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, class: 'form-control' %>
  </div>
  <%= submit_tag "Login", class: 'btn btn-primary' %>
  <%= link_to "Sign Up", signup_path, class: "btn btn-success"%>
<% end %>

app/views/signup/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, url: signup_path do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit "Register", class: 'btn btn-success' %>
<% end %>

app/views/students/edit.html.erb
<h1>Editing <%= @student.name %> </h1>

<%= form_for @student do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :photo_url %>
    <%= f.url_field :photo_url, class: 'form-control'%>
  </div>

  <%= f.submit class: 'btn btn-danger'%>
<% end %>

app/views/students/index.html.erb
<h1>Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        # Picks
      </th>
      <th>
        Last Picked
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td>
        <%= link_to student.name, student_path(student.id) %>
      </td>
      <td>
        <%= student.count %>
      </td>
      <td>
        <%= student.picks.last.created_at if student.picks.count > 0 %>
      </td>
      <td>
        <%= link_to "show", student_path(student.id), class: 'btn btn-default btn-xs' %>
        <%= link_to "✕", student_path(student.id), class: 'btn btn-danger btn-xs' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "PICK", pick_students_path, class: 'epic-btn', method: :post %>
<%= link_to "New Student", new_student_path, class: 'btn btn-success' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= form_for @student do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :photo_url %>
    <%= f.url_field :photo_url, class: 'form-control'%>
  </div>

  <%= f.submit class: 'btn btn-danger'%>
<% end %>

<%= link_to "Home", students_path, class: 'btn btn-default' %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<div class="row">
  <div class="col-md-3">
    <% unless @student.photo_url.blank? %>
      <%= image_tag @student.photo_url, class: "thumbnail img-responsive"%>
    <% else %>
      <%= image_tag "http://placekitten.com/500/500" , class: "thumbnail"%>
    <% end %>
  </div>

  <div class="col-md-9">
    <div class="btn-toolbar">
      <div class="btn-group">
        <%= link_to "Home", students_path, class: 'btn btn-default' %>
      </div>

      <%= link_to "Edit", edit_student_path(@student.id), class: 'btn btn-primary' %>
      <%= link_to "Delete", @student, method: :delete, class: 'btn btn-danger' %>
    </div>


    <table class="table table-bordered">
      <thead>
        <tr>
          <th>
            Picked
          </th>
          <th>
            Time Ago
          </th>
        </tr>
      </thead>
      <tbody>
        <% @student.picks.each do |pick|%>
        <tr>
          <td>
            <%= pick.created_at %>
          </td>
          <td>
            ?
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>